
const SET_SHOW_SIGN_MODEL = 'SET_SHOW_SIGN_MODEL'
const SET_CURRENT_DAY = 'SET_CURRENT_DAY'
const SET_CHOOSE_CLASS = 'SET_CHOOSE_CLASS'
const SET_SIGN_STATE = 'SET_SIGN_STATE'
const SET_AWARD_INFO = 'SET_AWARD_INFO'
const SET_MATCH_STATE = 'SET_MATCH_STATE'
const SET_BET_SUCCESS = 'SET_BET_SUCCESS'
const SET_BET_ERROR = 'SET_BET_ERROR'
const SET_BET_CAR = 'SET_BET_CAR'
const SET_BET_ITEM = 'SET_BET_ITEM'
const SET_USER_INFO = 'SET_USER_INFO'
const SET_CLOSE_BET_CAR = 'SET_CLOSE_BET_CAR'
const SET_GUESS_CENTER_INDEX = 'SET_GUESS_CENTER_INDEX'
const SET_EMPTY_BET_STATE = 'SET_EMPTY_BET_STATE'
const SET_CHANNEL_STATE = 'SET_CHANNEL_STATE'
const SET_AFFIRM_PAY_STATE = 'SET_AFFIRM_PAY_STATE'
const SET_SUBMIT_AFFIRM_GOLD = 'SET_SUBMIT_AFFIRM_GOLD'
const SET_VOLUME_STATE = 'SET_VOLUME_STATE'
const SET_PRODUCT_MSG = 'SET_PRODUCT_MSG'
const SET_ADDRESS_MSG = 'SET_ADDRESS_MSG'
export {
  SET_SHOW_SIGN_MODEL,
  SET_CURRENT_DAY,
  SET_CHOOSE_CLASS,
  SET_SIGN_STATE,
  SET_AWARD_INFO,
  SET_MATCH_STATE,
  SET_BET_SUCCESS,
  SET_BET_ERROR,
  SET_BET_CAR,
  SET_BET_ITEM,
  SET_USER_INFO,
  SET_CLOSE_BET_CAR,
  SET_GUESS_CENTER_INDEX,
  SET_EMPTY_BET_STATE,
  SET_CHANNEL_STATE,
  SET_AFFIRM_PAY_STATE,
  SET_SUBMIT_AFFIRM_GOLD,
  SET_VOLUME_STATE,
  SET_PRODUCT_MSG,
  SET_ADDRESS_MSG
}
