const state = {
  // 签到弹窗显示状态
  showSignModel: false,
  // 当前签到共计多少天（最大7天）
  currentday: 0,
  // 赛事中心，分类导航编辑弹窗状态
  chooseClaState: false,
  // 签到成功弹窗状态
  signState: false,
  // 签到奖励信息
  awardInfo: {},
  // 赛事内页，投注详情弹出层状态
  matchState: false,
  // 投注成功，弹窗状态
  betSuccess: false,
  // 投注失败，弹窗状态
  betError: false,
  // 投注框状态
  betCarState: false,
  // 投注选项
  betItem: {},
  // 用户财富信息
  userInfo: {},
  // 投注关闭确认弹窗
  closeBetCarState: false,
  // 竞猜中心索引
  guessCenterIndex: 1,
  // 清空投注金币状态
  emptyBetState: false,
  // 频道弹窗状态
  channelState: false,
  // 金币兑换确认弹窗
  affirmPayState: false,
  // 确认兑换金币
  submitAffurmGold: false,
  // 抽奖弹窗状态
  volumeState: false,
  // 商品信息
  productMsg: {},
  // 地址信息
  addrssMsg: {}
}
export default state
